//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EWPEntities : DbContext
    {
        public EWPEntities()
            : base("name=EWPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C1RM> C1RM { get; set; }
        public virtual DbSet<C1RMWorkout> C1RMWorkout { get; set; }
        public virtual DbSet<Bone> Bones { get; set; }
        public virtual DbSet<Injury> Injuries { get; set; }
        public virtual DbSet<Joint> Joints { get; set; }
        public virtual DbSet<Muscle> Muscles { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Workout> Workouts { get; set; }
        public virtual DbSet<WorkoutMuscle> WorkoutMuscles { get; set; }
        public virtual DbSet<WorkoutPlan> WorkoutPlans { get; set; }
    }
}
